# Generated by Django 3.0.8 on 2020-07-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troops', '0002_player_ki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ki',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ready', models.BooleanField(default=False)),
                ('game_players', models.ManyToManyField(to='troops.Player')),
            ],
        ),
    ]
