# Generated by Django 3.0.8 on 2020-07-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0004_auto_20200707_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
